In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day48-simple-linear-regression/placement.csv")
data.head(2)

cgpa  package
0  6.89     3.26
1  5.12     1.98

In [31]:
x_train = data['cgpa'].values.reshape(-1, 1)
y_train = data['package'].values.reshape(-1, 1)

In [32]:
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression()

In [33]:
lr_model.coef_

array([[0.56959129]])

In [34]:
lr_model.intercept_

array([-0.98567795])

In [35]:
lr_model.score(x_train, y_train)

0.7756192256051151

In [36]:
y_pred = lr_model.predict(x_train)

In [37]:
# Calculating R2 score
mae = mean_absolute_error(y_train, y_pred)
mse = mean_squared_error(y_train, y_pred)
r2 = r2_score(y_train, y_pred)

0.2596266083419547

In [20]:
# Adding a random column to see if r2 score gets increased
rand_col = np.random.rand(len(data), 1)

In [43]:
data_new = np.append(x_train, rand_col+3, axis=1)
data_new[: 3]

array([[6.89      , 3.36892908],
       [5.12      , 3.74014903],
       [7.82      , 3.39006158]])

In [44]:
lr2 = LinearRegression()
lr2.fit(data_new, y_train)

LinearRegression()

In [45]:
pred_new = lr2.predict(data_new)

In [47]:
# The r2 score has increased
r2_new = r2_score(y_train, pred_new)

In [48]:
n = len(data)

In [49]:
adj_r2 = 1 - ((1-r2)*(n-1)) / (n-1-1)
adj_r2

0.7744859893707975

In [51]:
# Adjusted r2 has decreased
adj_r2_new = 1 - ((1-r2_new)*(n-1)) / (n-1-2)
adj_r2_new

0.7738086425397477