In [22]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day48-simple-linear-regression/placement.csv")
data.head(2)

cgpa  package
0  6.89     3.26
1  5.12     1.98

In [33]:
px_plot = px.scatter(data, 
           x='cgpa',
           y='package')
go.Scatter(x=data['cgpa'], y=data['cgpa'], mode='lines')
combined_fig = go.Figure(data=[])

Scatter({
    'mode': 'lines',
    'x': array([6.89, 5.12, 7.82, 7.42, 6.94, 7.89, 6.73, 6.75, 6.09, 8.31, 5.32, 6.61,
                8.94, 6.93, 7.73, 7.25, 6.84, 5.38, 6.94, 7.48, 7.28, 6.85, 6.14, 6.19,
                6.53, 7.28, 8.31, 5.42, 5.94, 7.15, 7.36, 8.1 , 6.96, 6.35, 7.34, 6.87,
                5.99, 5.9 , 8.62, 7.43, 9.38, 6.89, 5.95, 7.66, 5.09, 7.87, 6.07, 5.84,
                8.63, 8.87, 9.58, 9.26, 8.37, 6.47, 6.86, 8.2 , 5.84, 6.6 , 6.92, 7.56,
                5.61, 5.48, 6.34, 9.16, 7.36, 7.6 , 5.11, 6.51, 7.56, 7.3 , 5.79, 7.47,
                7.78, 8.44, 6.85, 6.97, 6.94, 8.99, 6.59, 7.18, 7.63, 6.1 , 5.58, 8.44,
                4.26, 4.79, 7.61, 8.09, 4.73, 6.42, 7.11, 6.22, 7.9 , 6.79, 5.83, 6.63,
                7.11, 5.98, 7.69, 6.61, 7.95, 6.71, 5.13, 7.05, 7.62, 6.66, 6.13, 6.33,
                7.76, 7.77, 8.18, 5.42, 8.58, 6.94, 5.84, 8.35, 9.04, 7.12, 7.4 , 7.39,
                5.23, 6.5 , 5.12, 5.1 , 6.06, 7.33, 5.91, 6.78, 7.93, 7.29, 6.68, 6.37,
 

In [20]:
lr_model = LinearRegression()
lr_model.fit(data['cgpa'].values.reshape(-1, 1), data['package'].values.reshape(-1, 1))

LinearRegression()

In [21]:
lr_model.coef_

array([[0.56959129]])

In [19]:
[data['cgpa']]

[0      6.89
 1      5.12
 2      7.82
 3      7.42
 4      6.94
        ... 
 195    6.93
 196    5.89
 197    7.21
 198    7.63
 199    6.22
 Name: cgpa, Length: 200, dtype: float64]

In [25]:
lr_model.intercept_

array([-0.98567795])

In [26]:
lr_model.coef_

array([[0.56959129]])

In [29]:
lr_model.score(data['cgpa'].values.reshape(-1, 1), data['package'].values.reshape(-1, 1))

0.7756192256051151