In [6]:
import numpy as np
import pandas as pd

import plotly.express as px

from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [22]:
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=0.4)
df = pd.DataFrame({'feature1':X[:, 0], 'feature2':X[:, 1], 'target':y})
df.head()

feature1  feature2     target
0 -0.589201 -0.258795 -27.711560
1  0.647423 -0.152971   3.597658
2  1.451711 -1.334892 -53.145597
3  1.516930  0.925949  88.965788
4 -0.595530  0.340520   9.221287

In [10]:
px.scatter_3d(x=X[:, 0], y=X[:, 1], z=y)

In [11]:
lr = LinearRegression()
lr.fit(X, y)


LinearRegression()

In [12]:
y_pred = lr.predict(X)

In [13]:
mean_absolute_error(y, y_pred)

28.023020432557242

In [15]:
np.sqrt(mean_squared_error(y, y_pred))

35.27625339229429

In [16]:
r2_score(y, y_pred)

0.8307851249218288

In [17]:
lr.coef_

array([61.30213715, 65.77932608])

In [18]:
lr.intercept_

-1.4114365617258002

Diabetes dataset

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
X, y = load_diabetes(return_X_y=True)

In [4]:
X.shape

(442, 10)

In [8]:
lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [9]:
y_pred = lr.predict(X)

In [10]:
print('MAE', mean_absolute_error(y, y_pred))
print('MsE', mean_squared_error(y, y_pred))
print('R2', r2_score(y, y_pred))

MAE 43.27745202531506
MsE 2859.69634758675
R2 0.5177484222203499


In [11]:
lr.coef_

array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
       -792.17563855,  476.73902101,  101.04326794,  177.06323767,
        751.27369956,   67.62669218])

In [12]:
lr.intercept_

152.13348416289597

In [15]:
X.ravel()

array([ 0.03807591,  0.05068012,  0.06169621, ..., -0.03949338,
       -0.00422151,  0.00306441])

In [32]:
n_sample = 105
batch_size = 10
batches = np.random.choice(np.arange(0, n_sample), size= [int(n_sample/batch_size), 10], replace=False)

In [33]:
data = np.arange(0, n_sample).reshape(-1, 1)
data[batches[0]]

array([[ 87],
       [ 77],
       [ 58],
       [ 86],
       [ 33],
       [100],
       [ 50],
       [ 44],
       [ 52],
       [ 48]])